/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        osprey.competition.knockout.ImageViewer.main(args);
    }
}
